# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCI Recovery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SCI Recovery
  pod 'AFNetworking', '~> 3.0'
  #pod 'FBSDKCoreKit', '~> 4.9'
  pod 'Alamofire', '~> 5.4'
  source 'https://github.com/CocoaPods/Specs.git'
  #pod 'HS-Font-Icons'
  pod 'MaterialDesignSymbol'

  target 'SCI RecoveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCI RecoveryUITests' do
    # Pods for testing
  end

end
